version: '3'

services:
  merliondnode0:
    container_name: merliondnode0
    image: "merlionzone/localnetnode"
    ports:
      - "26656-26657:26656-26657"
      - "8545-8546:8545-8546"
      - "9090-9091:9090-9091"
    environment:
      - ID=0
      - LOG=${LOG:-merliond.log}
    volumes:
      - ./build:/merlion:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  merliondnode1:
    container_name: merliondnode1
    image: "merlionzone/localnetnode"
    ports:
      - "26659-26660:26656-26657"
      - "8547-8548:8545-8546"
    environment:
      - ID=1
      - LOG=${LOG:-merliond.log}
    volumes:
      - ./build:/merlion:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  merliondnode2:
    container_name: merliondnode2
    image: "merlionzone/localnetnode"
    environment:
      - ID=2
      - LOG=${LOG:-merliond.log}
    ports:
      - "26661-26662:26656-26657"
      - "8549-8550:8545-8546"
    volumes:
      - ./build:/merlion:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  merliondnode3:
    container_name: merliondnode3
    image: "merlionzone/localnetnode"
    environment:
      - ID=3
      - LOG=${LOG:-merliond.log}
    ports:
      - "26663-26664:26656-26657"
      - "8551-8552:8545-8546"
    volumes:
      - ./build:/merlion:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/16
